run:
  timeout: 5m
linters:
  enable:
    - govet
    - gofmt
    - goimports
    - gosimple
    - staticcheck
    - ineffassign
    - errcheck
    - misspell
    - revive
issues:
  exclude-use-default: false
